version: "1"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: api #DB KAN GEDEFINIEERD WORDEN.
      DATABASE_URL: postgresql://user-name:strong-password@db/tapi
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  postman:
    build:
      context: .
      args:
        - POSTMAN_API_KEY_ARG=${POSTMAN_API_KEY}

  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/api
    environment:
      DATABASE_URL: postgresql://user-name:strong-password@db/tapi

  

volumes:
  local_pgdata:
  pgadmin-data: