version: "1"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: root
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/api
    environment:
      DATABASE_URL: postgresql://root:strong-password@db/root
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  local_pgdata:
  pgadmin-data: