"""added test

Revision ID: 262f9cceae01
Revises: 7120166138a7
Create Date: 2024-01-25 12:56:52.094888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262f9cceae01'
down_revision: Union[str, None] = '7120166138a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cover_soort', ['naam'])
    op.add_column('karakter', sa.Column('test', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'karakter', ['naam'])
    op.create_unique_constraint(None, 'serie', ['naam'])
    op.create_unique_constraint(None, 'stripboek', ['naam'])
    op.create_unique_constraint(None, 'uitgever', ['naam'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uitgever', type_='unique')
    op.drop_constraint(None, 'stripboek', type_='unique')
    op.drop_constraint(None, 'serie', type_='unique')
    op.drop_constraint(None, 'karakter', type_='unique')
    op.drop_column('karakter', 'test')
    op.drop_constraint(None, 'cover_soort', type_='unique')
    # ### end Alembic commands ###
