"""first revision

Revision ID: 7120166138a7
Revises: 
Create Date: 2024-01-25 10:18:02.185921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7120166138a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_soort',
    sa.Column('naam', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('naam'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('karakter',
    sa.Column('naam', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('naam'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('stripboek',
    sa.Column('naam', sa.String(), nullable=False),
    sa.Column('issueNummer', sa.Integer(), nullable=False),
    sa.Column('Uitgavedatum', sa.Date(), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('prijs', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('naam'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('uitgever',
    sa.Column('naam', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('naam'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('serie',
    sa.Column('naam', sa.String(), nullable=False),
    sa.Column('serieGrootte', sa.Integer(), nullable=True),
    sa.Column('uitgever_naam', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uitgever_naam'], ['uitgever.naam'], ),
    sa.PrimaryKeyConstraint('naam'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('strip_cover',
    sa.Column('stripboek', sa.String(), nullable=False),
    sa.Column('cover_soort', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cover_soort'], ['cover_soort.naam'], ),
    sa.ForeignKeyConstraint(['stripboek'], ['stripboek.naam'], ),
    sa.PrimaryKeyConstraint('stripboek', 'cover_soort')
    )
    op.create_table('strip_kar',
    sa.Column('stripboek', sa.String(), nullable=False),
    sa.Column('karakter', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['karakter'], ['karakter.naam'], ),
    sa.ForeignKeyConstraint(['stripboek'], ['stripboek.naam'], ),
    sa.PrimaryKeyConstraint('stripboek', 'karakter')
    )
    op.create_table('serie_strip',
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('stripboek', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['serie'], ['serie.naam'], ),
    sa.ForeignKeyConstraint(['stripboek'], ['stripboek.naam'], ),
    sa.PrimaryKeyConstraint('serie', 'stripboek')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie_strip')
    op.drop_table('strip_kar')
    op.drop_table('strip_cover')
    op.drop_table('serie')
    op.drop_table('uitgever')
    op.drop_table('stripboek')
    op.drop_table('karakter')
    op.drop_table('cover_soort')
    # ### end Alembic commands ###
