"""Changed to english

Revision ID: ab9df3f2aa6c
Revises: d8ecb41978e3
Create Date: 2024-02-01 13:40:12.150302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9df3f2aa6c'
down_revision: Union[str, None] = 'd8ecb41978e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie_strip')
    op.drop_table('strip_kar')
    op.drop_table('uitgever')
    op.drop_table('serie')
    op.drop_table('cover_soort')
    op.drop_table('stripboek')
    op.drop_table('karakter')
    op.drop_table('strip_cover')
    op.create_unique_constraint(None, 'characters', ['name'])
    op.create_unique_constraint(None, 'comics', ['name'])
    op.create_unique_constraint(None, 'covers', ['type'])
    op.create_unique_constraint(None, 'publishers', ['name'])
    op.create_unique_constraint(None, 'series', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series', type_='unique')
    op.drop_constraint(None, 'publishers', type_='unique')
    op.drop_constraint(None, 'covers', type_='unique')
    op.drop_constraint(None, 'comics', type_='unique')
    op.drop_constraint(None, 'characters', type_='unique')
    op.create_table('strip_cover',
    sa.Column('stripboek', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cover_soort', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cover_soort'], ['cover_soort.naam'], name='strip_cover_cover_soort_fkey'),
    sa.ForeignKeyConstraint(['stripboek'], ['stripboek.naam'], name='strip_cover_stripboek_fkey'),
    sa.PrimaryKeyConstraint('stripboek', 'cover_soort', name='strip_cover_pkey')
    )
    op.create_table('karakter',
    sa.Column('naam', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('naam', name='karakter_pkey'),
    sa.UniqueConstraint('naam', name='karakter_naam_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('stripboek',
    sa.Column('naam', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('issueNummer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Uitgavedatum', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('paginas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prijs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('naam', name='stripboek_pkey'),
    sa.UniqueConstraint('naam', name='stripboek_naam_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cover_soort',
    sa.Column('naam', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('naam', name='cover_soort_pkey'),
    sa.UniqueConstraint('naam', name='cover_soort_naam_key')
    )
    op.create_table('serie',
    sa.Column('naam', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('serieGrootte', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uitgever_naam', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uitgever_naam'], ['uitgever.naam'], name='serie_uitgever_naam_fkey'),
    sa.PrimaryKeyConstraint('naam', name='serie_pkey'),
    sa.UniqueConstraint('naam', name='serie_naam_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('uitgever',
    sa.Column('naam', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('naam', name='uitgever_pkey'),
    sa.UniqueConstraint('naam', name='uitgever_naam_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('strip_kar',
    sa.Column('stripboek', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('karakter', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['karakter'], ['karakter.naam'], name='strip_kar_karakter_fkey'),
    sa.ForeignKeyConstraint(['stripboek'], ['stripboek.naam'], name='strip_kar_stripboek_fkey'),
    sa.PrimaryKeyConstraint('stripboek', 'karakter', name='strip_kar_pkey')
    )
    op.create_table('serie_strip',
    sa.Column('serie', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stripboek', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['serie'], ['serie.naam'], name='serie_strip_serie_fkey'),
    sa.ForeignKeyConstraint(['stripboek'], ['stripboek.naam'], name='serie_strip_stripboek_fkey'),
    sa.PrimaryKeyConstraint('serie', 'stripboek', name='serie_strip_pkey')
    )
    # ### end Alembic commands ###
