"""Second revision

Revision ID: dbcdee283e1e
Revises: ec36086c75f6
Create Date: 2024-02-01 14:28:43.335196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcdee283e1e'
down_revision: Union[str, None] = 'ec36086c75f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'characters', ['name'])
    op.create_unique_constraint(None, 'comics', ['name'])
    op.create_unique_constraint(None, 'covers', ['type'])
    op.create_unique_constraint(None, 'publishers', ['name'])
    op.create_unique_constraint(None, 'series', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series', type_='unique')
    op.drop_constraint(None, 'publishers', type_='unique')
    op.drop_constraint(None, 'covers', type_='unique')
    op.drop_constraint(None, 'comics', type_='unique')
    op.drop_constraint(None, 'characters', type_='unique')
    # ### end Alembic commands ###
