"""First revision

Revision ID: ec36086c75f6
Revises: 
Create Date: 2024-02-01 14:19:01.884574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec36086c75f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comics',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issue', sa.Integer(), nullable=False),
    sa.Column('release', sa.Date(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('covers',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type'),
    sa.UniqueConstraint('type')
    )
    op.create_table('publishers',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comics_char',
    sa.Column('comics', sa.String(), nullable=False),
    sa.Column('characters', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['characters'], ['characters.name'], ),
    sa.ForeignKeyConstraint(['comics'], ['comics.name'], ),
    sa.PrimaryKeyConstraint('comics', 'characters')
    )
    op.create_table('comics_covers',
    sa.Column('comics', sa.String(), nullable=False),
    sa.Column('covers', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comics'], ['comics.name'], ),
    sa.ForeignKeyConstraint(['covers'], ['covers.type'], ),
    sa.PrimaryKeyConstraint('comics', 'covers')
    )
    op.create_table('series',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['publisher'], ['publishers.name'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('series_comics',
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('comics', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comics'], ['comics.name'], ),
    sa.ForeignKeyConstraint(['series'], ['series.name'], ),
    sa.PrimaryKeyConstraint('series', 'comics')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_comics')
    op.drop_table('series')
    op.drop_table('comics_covers')
    op.drop_table('comics_char')
    op.drop_table('publishers')
    op.drop_table('covers')
    op.drop_table('comics')
    op.drop_table('characters')
    # ### end Alembic commands ###
