on:
  push:
    branches:
      - terraform

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - name: Build image 
      #   run: docker build -t registry.digitalocean.com/dev-ops-novi-api/api:$(echo $GITHUB_SHA | head -c7) .

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      
      # - name: Push image to DO Container Registry 
      #   run: docker push registry.digitalocean.com/dev-ops-novi-api/api:$(echo $GITHUB_SHA | head -c7)

      - name: navigate to Terrafom folder before setup
        run: |
          cd config

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: |
          cd config
          terraform init

      - name: Terraform Apply
        run: |
          cd config
          terraform apply -auto-approve \
            -var "DATABASE_URL=$(doctl databases connection $(doctl databases list --format ID --no-header) --format URI --no-header)" \
            -var "DIGITALOCEAN_TOKEN=${{ secrets.DIGITALOCEAN_TOKEN }}"