on:
  push:
    branches:
      - terraform

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2

      # - name: Install doctl 
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - name: Build image 
      #   run: docker build -t registry.digitalocean.com/dev-ops-novi-api/api:$(echo $GITHUB_SHA | head -c7) .

      # - name: Log in to DO Container Registry 
      #   run: doctl registry login --expiry-seconds 600
      
      # - name: Push image to DO Container Registry 
      #   run: docker push registry.digitalocean.com/dev-ops-novi-api/api:$(echo $GITHUB_SHA | head -c7)

      - name: folder structure
        run: ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0
          
      - name: Navigate to Terraform directory
        run: cd config

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          DATABASE_URL: $(doctl databases connection $(doctl databases list --format ID --no-header) --format URI --no-header)


