name: docker

on: 
  push:
    branches: [main]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v3
    
    - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
    - name: Create and activate venv
      run: |
        python -m venv ATY
        source ATY/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #- name: Analysing the code with pylint
    #  run: |
    #    pylint --fail-under=8 $(git ls-files '*.py')
