name: integration test development

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
env:
  DATABASE_URL: postgresql://user:password@localhost:5432/api
jobs:
  integration_tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api
        ports:
          - 5432:5432
        volumes:
          - local_pgdata:/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.13"
          
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run pytest
        run: |
          pytest