name: integration test development

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compose docker db container
        run: |
          docker-compose up -d db
          # Wait for the db container to be healthy
          until docker inspect --format "{{json .State.Health.Status }}" db | grep -q healthy; do
            echo "Waiting for db container to be healthy..."
            sleep 5
          done
          echo "db container is healthy!"

      - name: Compose docker api container
        run: |
          docker-compose up -d api
          # Wait for the api container to be healthy
          until docker inspect --format "{{json .State.Health.Status }}" api | grep -q healthy; do
            echo "Waiting for api container to be healthy..."
            sleep 5
          done
          echo "api container is healthy!"
      
      - name: Run pytest
        run: |
          docker exec api pytest