name: integration test development

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compose docker db container
        run: |
          docker compose up db -d

      - name: Compose docker api container
        run: |
          docker compose up api -d
      
      - name: Run pytest
        run: |
          docker compose run api pytest tests/