name: integration test development

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compose docker
        run: |
          docker compose up -d

      - name: check docker names
        run: |
          docker ps
      
      - name: Run pytest
        run: |
          docker exec devops-novi-api-1 pytest tests/