name: integration test development

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: user-name
          POSTGRES_PASSWORD: strong-password
          POSTGRES_DB: api
        volumes:
          - local_pgdata:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker containers
        run: |
          docker build -t api-test .
          docker run -d --name api-container -p 8000:8000 --network=host api-test

      - name: Wait for API to be ready
        run: docker exec api-container sh -c 'while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8000)" != "200" ]; do sleep 1; done'

      - name: Run Pytest
        run: |
          pip install requirements.txt
          
          touch supervisord.conf
          cat > supervisord.conf << EOL
          [supervisord]

          [fcgi-program:uvicorn]
          socket=tcp://localhost:8080
          command=/opt/hostedtoolcache/Python/3.10.13/x64/bin/uvicorn --fd 0 app.main:app
          numprocs=4
          process_name=uvicorn-%(process_num)d
          stdout_logfile=/dev/stdout
          stdout_logfile_maxbytes=0
          EOL
          supervisord
          sleep 3
          pytest

      - name: Cleanup
        run: |
          docker stop api-container
          docker rm api-container      