name: pipeline
on:
  pull_request:
    branches:
      - 'development'
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
    
      - name: Compose docker
        run: docker compose up -d

      - name: check docker names
        run: docker ps

      - name: access localhost
        run: curl http://0.0.0.0:8000
