name: unittestDevelopment

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Create and activate venv
        run: |
          python -m venv ATY
          source ATY/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest

      - name: Check pytest result
        if: always()  # This ensures the step runs even if previous steps fail
        run: exit $(test -f pytest-failed && cat pytest-failed || echo 0)

      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      
      - name: Run API tests
        run: |
          # Lint your API using Postman CLI
          postman api lint e5b4ed5a-77a2-48e3-aa86-e9bde82de358 --integration-id 155264    